In [10]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [5]:
#create
arr1=np.zeros((2,3)) #prefill
print(arr1,arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [7]:
arr5=np.linspace(1,100,4)
print(arr5)

[  1.  34.  67. 100.]


In [13]:
arr=np.array([[1,2,3,4,5,6],[1,2,3,4,5,4]])
print(arr.shape)
print(arr.dtype)

(2, 6)
int64


In [5]:
#operation on arrays
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped)

idx=[0]
flat=arr.flatten()
print(flat)

print(arr[idx])

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2 3]]


In [6]:
arr=np.array([1,2,3,4,5])
arr2=arr**2

print(arr2)

[ 1  4  9 16 25]


In [7]:
 #brodcasting
print(arr*5)

[ 5 10 15 20 25]


In [15]:
#normalize

arrs=np.array([[1,2],[3,4]])

mean=np.mean(arrs)
std=np.std(arrs)

norms=(arrs-mean)/std
print(norms)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [20]:
print(np.trunc(3.55))

3.0
